builds:
  - binary: switch-traffic-to-mackerel
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - config.yaml.sample
release:
  github:
    owner: yseto
    name: switch-traffic-to-mackerel
